# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QHeaderView


class Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1910, 1000)

        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 0, 1890, 980))
        self.table.verticalHeader().setVisible(False)
        self.table.setObjectName("table")
        self.table.setColumnCount(11)
        self.table.setRowCount(0)

        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setSectionResizeMode(4, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.table.horizontalHeader().setSectionResizeMode(5, QHeaderView.ResizeMode.Stretch)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setSectionResizeMode(6, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        self.table.horizontalHeader().setSectionResizeMode(7, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setSectionResizeMode(8, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        self.table.horizontalHeader().setSectionResizeMode(9, QHeaderView.ResizeMode.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(10, item)
        self.table.horizontalHeader().setSectionResizeMode(10, QHeaderView.ResizeMode.ResizeToContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        font = QFont()
        font.setBold(True)
        Form.setWindowTitle(_translate("Form", "Процессы Windows"))
        item = self.table.horizontalHeaderItem(0)
        item.setFont(font)
        item.setText(_translate("Form", "PID"))
        item = self.table.horizontalHeaderItem(1)
        item.setFont(font)
        item.setText(_translate("Form", "Имя"))
        item = self.table.horizontalHeaderItem(2)
        item.setFont(font)
        item.setText(_translate("Form", "Статус"))
        item = self.table.horizontalHeaderItem(3)
        item.setFont(font)
        item.setText(_translate("Form", "Родитель"))
        item = self.table.horizontalHeaderItem(4)
        item.setFont(font)
        item.setText(_translate("Form", "Исполняемый файл"))
        item = self.table.horizontalHeaderItem(5)
        item.setFont(font)
        item.setText(_translate("Form", "DLL"))
        item = self.table.horizontalHeaderItem(6)
        item.setFont(font)
        item.setText(_translate("Form", "Владелец"))
        item = self.table.horizontalHeaderItem(7)
        item.setFont(font)
        item.setText(_translate("Form", "SID"))
        item = self.table.horizontalHeaderItem(8)
        item.setFont(font)
        item.setText(_translate("Form", "Архитектура"))
        item = self.table.horizontalHeaderItem(9)
        item.setFont(font)
        item.setText(_translate("Form", "DEP"))
        item = self.table.horizontalHeaderItem(10)
        item.setFont(font)
        item.setText(_translate("Form", "ASLR"))
